Repository herbsjs/herbsjs.github.io, pull requests merged in 2021-12, with the labels that each got.

#84 add id field documentation and update docusaurus version for sec updates
  docs/entity/features.md
  docs/entity/getting-started.md
  docs/entity/validation.md
  package-lock.json
  package.json
  src/pages/styles.module.css
Labels: documentation

#83 Section How to contribute
  docs/project/contributing.md
  static/img/example_code_download.png
Labels: documentation, severity-major, wip

#91 fix: add correct link at "CONTRIBUTING" and "MIT License" in Herbs2gql Glue
  docs/glues/herbs2gql.md
Labels: bug, documentation, severity-minor, released
