Repository herbsjs/herbsjs.github.io, pull requests merged in 2022-01, with the labels that each got.

#93 update version of docusarus and fix missed link
  docs/entity/getting-started.md
  package-lock.json
  package.json
  sidebars.js
Labels: dependencies, severity-minor

#92 feat: adding cheat sheet in "How to contributing"
  docs/project/contributing.md
  package-lock.json
  static/img/cheatsheet.JPG
Labels: documentation, severity-minor, released

#101 Fix gtag
  docusaurus.config.js
  package-lock.json
  package.json
Labels: bug, severity-major

#106 upgrade docusaurus version
  package-lock.json
  package.json
  src/pages/indexComponents/banner/banner.js
Labels: dependencies, severity-minor
